In [2]:
import pandas as pd
import numpy as np
import os
%matplotlib inline

In [9]:
df=pd.read_csv('Project_data.csv')
print(df.shape)
df.head()
print(len(np.unique(df.SUPERVISOR)))

(2761, 7)
529

In [4]:
df.drop(columns=['PROJECT_CREATED','PROJECT_DELETED'],inplace=True)
df.head()

,SUPERVISOR,PROJECT_TITLE,PROJECT_DESCRIPTION,COURSES,PROJECT_TAGS
0,Amanda Dowd,Student Defined Project in the area of Educati...,The areas that I would be interested in superv...,"e-BM - Electronic-Business Management,ITM - In...","Information management,Social media,eBusiness,..."
1,Amanda Dowd,The use of on-line technology in academic cour...,INTRODUCTION\r\n\r\nWith increasing numbers of...,"e-BM - Electronic-Business Management,PPM - Pr...","Programme management,Information management,eB..."
2,Nigel Denton,Student proposed project normally in Engineeri...,If you are thinking about a project in the are...,"e-BM - Electronic-Business Management,EngBM - ...","eBusiness,Financial issues,Innovation,Entrepre..."
3,Des Doran,Sustainable Operations,Exploring the impact of sustainable issues upo...,"e-BM - Electronic-Business Management,EngBM - ...","Operational issues,Sustainability,Sustainable ..."
4,Des Doran,Operations Strategy,This project should explore how strategic posi...,"e-BM - Electronic-Business Management,EngBM - ...","Supply chain,Operational issues,Strategic mana..."

In [5]:
df.drop(columns=['PROJECT_CREATED','PROJECT_DELETED'],inplace=True)
df.isnull().sum(axis=0)

KeyError: "['PROJECT_CREATED' 'PROJECT_DELETED'] not found in axis"

In [5]:
df["PROJECT_TITLE"] = df["PROJECT_TITLE"].fillna("Blank")
df["COURSES"] = df["COURSES"].fillna("Blank")
df.isnull().sum(axis=0)

SUPERVISOR             0
PROJECT_TITLE          0
PROJECT_DESCRIPTION    0
COURSES                0
PROJECT_TAGS           0
dtype: int64

In [6]:
def course_check(project_tags,tag):
    if tag in project_tags:
        return 1
    else:
        return 0

df["check"]= df.apply(lambda x: course_check(x.COURSES,"e-BM - Electronic-Business Management"),axis =1 )
                       
df.head()

,SUPERVISOR,PROJECT_TITLE,PROJECT_DESCRIPTION,COURSES,PROJECT_TAGS,check
0,Amanda Dowd,Student Defined Project in the area of Educati...,The areas that I would be interested in superv...,"e-BM - Electronic-Business Management,ITM - In...","Information management,Social media,eBusiness,...",1
1,Amanda Dowd,The use of on-line technology in academic cour...,INTRODUCTION\r\n\r\nWith increasing numbers of...,"e-BM - Electronic-Business Management,PPM - Pr...","Programme management,Information management,eB...",1
2,Nigel Denton,Student proposed project normally in Engineeri...,If you are thinking about a project in the are...,"e-BM - Electronic-Business Management,EngBM - ...","eBusiness,Financial issues,Innovation,Entrepre...",1
3,Des Doran,Sustainable Operations,Exploring the impact of sustainable issues upo...,"e-BM - Electronic-Business Management,EngBM - ...","Operational issues,Sustainability,Sustainable ...",1
4,Des Doran,Operations Strategy,This project should explore how strategic posi...,"e-BM - Electronic-Business Management,EngBM - ...","Supply chain,Operational issues,Strategic mana...",1

In [7]:
df=df.drop(index=(df.loc[(df['check']==0)].index))
df.head()
print(df.shape)
df.to_csv("eBM_data.csv", index=False)

(737, 6)

In [8]:
Tag_list=[]
for tags in df.PROJECT_TAGS:
    taglist=tags.split(",")
    for tag in taglist:
        Tag_list.append(tag)
Tag_final_list=np.unique(Tag_list)
Supervisor_list=np.unique(df.SUPERVISOR)
print(len(Tag_final_list))
print(len(Supervisor_list))

266
219

In [9]:
print(len(df.SUPERVISOR))
i=1
id_list=[]
while i <=737:
    id_list.append(i)
    i=i+1
df['project_id']=id_list
df.drop(columns=['COURSES','check'],inplace=True)
print(df.shape)
df.head()

(737, 5)

,SUPERVISOR,PROJECT_TITLE,PROJECT_DESCRIPTION,PROJECT_TAGS,project_id
0,Amanda Dowd,Student Defined Project in the area of Educati...,The areas that I would be interested in superv...,"Information management,Social media,eBusiness,...",1
1,Amanda Dowd,The use of on-line technology in academic cour...,INTRODUCTION\r\n\r\nWith increasing numbers of...,"Programme management,Information management,eB...",2
2,Nigel Denton,Student proposed project normally in Engineeri...,If you are thinking about a project in the are...,"eBusiness,Financial issues,Innovation,Entrepre...",3
3,Des Doran,Sustainable Operations,Exploring the impact of sustainable issues upo...,"Operational issues,Sustainability,Sustainable ...",4
4,Des Doran,Operations Strategy,This project should explore how strategic posi...,"Supply chain,Operational issues,Strategic mana...",5

In [9]:
import numpy as np
SUPERVISOR_list=np.unique(df['SUPERVISOR'])
print(len(SUPERVISOR_list))

i=1
id_list=[]
while i <=737:
    id_list.append(i)
    i=i+1
df['project_id']=id_list
df.drop(columns=['COURSES','check'],inplace=True)

df["supervisor_id"]=df["SUPERVISOR"]
supervisor_id=1

for supervisor in SUPERVISOR_list: 

    df.supervisor_id.replace([supervisor], [supervisor_id], inplace=True)
    supervisor_id=supervisor_id+1
    
df.head()

219

,SUPERVISOR,PROJECT_TITLE,PROJECT_DESCRIPTION,PROJECT_TAGS,project_id,supervisor_id
0,Amanda Dowd,Student Defined Project in the area of Educati...,The areas that I would be interested in superv...,"Information management,Social media,eBusiness,...",1,12
1,Amanda Dowd,The use of on-line technology in academic cour...,INTRODUCTION\r\n\r\nWith increasing numbers of...,"Programme management,Information management,eB...",2,12
2,Nigel Denton,Student proposed project normally in Engineeri...,If you are thinking about a project in the are...,"eBusiness,Financial issues,Innovation,Entrepre...",3,159
3,Des Doran,Sustainable Operations,Exploring the impact of sustainable issues upo...,"Operational issues,Sustainability,Sustainable ...",4,58
4,Des Doran,Operations Strategy,This project should explore how strategic posi...,"Supply chain,Operational issues,Strategic mana...",5,58

In [10]:
Tag_list=[]
for tags in df.PROJECT_TAGS:
    taglist=tags.split(",")
    for tag in taglist:
        Tag_list.append(tag)
Tag_final_list=np.unique(Tag_list)
print(Tag_final_list)

['AR-VR' 'Accountancy' 'Action Research' 'Aeronautical' 'Aerospace'
 'Africa' 'Agile' 'Analysis' 'App development'
 'Artificial Intelligence (AI)' 'Asia' 'Assessment' 'Assets' 'Automation'
 'Automotive' 'Autonomous Vehicles' 'Aviation' 'Balancing'
 'Battery manufacture' 'Battery materials' 'Battery modelling'
 'Battery testing and characterisation' 'Behavioural study'
 'Best practice' 'Blockchain' 'Branding' 'Brexit' 'Britain' 'Business'
 'Business Excellence' 'Business administration' 'Business model'
 'Business practices' 'Business support' 'Carbon management'
 'Change management' 'Chemical' 'Circular economy' 'Cloud' 'Collaboration'
 'Commercial' 'Communications' 'Comparative analysis' 'Competences'
 'Competitive' 'Compiled computer languages' 'Complex'
 'Computer programming' 'Computing' 'Connectivity' 'Construction'
 'Contracts' 'Control systems' 'Corporate Social Reponsibility'
 'Creative thinking' 'Cultural' 'Cyber certification'
 'Cyber-physical Systems' 'Cybersecurity' 'Data accuracy' 'Data analytics'
 'Data presentation' 'Data protection' 'Decision making' 'Design'
 'Development' 'Disruptive' 'Economics' 'Education' 'Efficiency'
 'Electric vehicle' 'Emerging' 'Energy' 'Engineering administration'
 'Engineering application' 'Engineering industries'
 'Engineering practices' 'Enterprise' 'Entrepreneurship' 'Environmental'
 'Espionage' 'Ethics' 'European' 'Eurozone' 'Events'
 'Expectation Management' 'FMCG companies' 'Failure' 'Fair trade'
 'Family business' 'Finance' 'Financial issues' 'Forecasting' 'Franchise'
 'Fulfillment' 'Future' 'Global' 'Governance' 'Growth' 'Healthcare'
 'Human aspects of information security' 'Human machine interface'
 'Human resources' 'Hybrid Vehicles'
 'ICT - Information and communications technology' 'ISO standards'
 'IT Governance' 'Impact analysis' 'Improvement' 'In-company application'
 'Individual' 'Industry 4.0' 'Information management'
 'Information security' 'Infrastructure' 'Innovation' 'Intangible assets'
 'Integration' 'Intellectual Property' 'Intellectual capital'
 'International' 'Internet' 'Internet of Things (IoT)'
 'Interpreted computer languages' 'Interviews' 'Inventory' 'Investigative'
 'Investment' 'Joint venture' 'Kaizen' 'Key Performance Indicators - KPI'
 'Knowledge management' 'Knowledge transfer' 'Leadership' 'Lean' 'Legacy'
 'Legal' 'Lightweighting' 'Literature Review' 'Local' 'Logistics'
 'Machine Learning' 'Maintenance engineering' 'Management' 'Manufacturing'
 'Manufacturing systems' 'Market definition' 'Market evaluation'
 'Marketing' 'Markets' 'Material' 'Methodologies' 'Mining'
 'Mixed methods analysis' 'Modelling' 'Monetisation' 'Motivation' 'NGO'
 'National' 'Natural resources' 'Negotiation' 'Network defence'
 'North America' 'Not for profit' 'Oil and gas' 'Omni-channel management'
 'On-Shelf Availability' 'Operational issues' 'Operations Management'
 'Operations Strategy' 'Optimisation' 'Organisational behaviour'
 'Organisational development' 'Organisational learning' 'Outsourcing'
 'Patents' 'Performance' 'Pharmaceutical' 'Planning' 'Policy'
 'Portfolio management' 'Prince2' 'Problem' 'Process'
 'Process Improvement' 'Procurement' 'Product development' 'Production'
 'Professional development' 'Programme management' 'Programme risk'
 'Project finance' 'Project management' 'Project risk' 'Property'
 'Propulsion' 'Purchasing' 'Qualitative analysis' 'Quality Management'
 'Quantitative analysis' 'Rail' 'Recycling' 'Reengineering' 'Regional'
 'Renewable energy' 'Reputation' 'Research' 'Resource'
 'Resource management' 'Retail supply chain management' 'Risk Management'
 'Risk evaluation' 'SERVQUAL' 'SMEs' 'Safety analysis' 'Sales' 'Scenario'
 'Security' 'Security architectures' 'Services' 'Shipping' 'Simulation'
 'Six Sigma' 'Smart vehicles' 'Social media' 'Society'
 'Software development' 'South America' 'Sponsor' 'Stakeholder Management'
 'Start-up' 'Statistical analysis' 'Statistical modelling'
 'Strategic management' 'Strategy' 'Structure' 'Student defined project'
 'Supply chain' 'Support' 'Sustainability' 'Sustainable Operations'
 'Systems Thinking' 'Systems engineering' 'Team' 'Technical management'
 'Technology' 'Test project tag' 'Testing' 'Tools' 'Trade' 'Training'
 'Transport' 'UK' 'Value' 'Venture' 'Verification and validation'
 'Warehousing' 'Web 2.0' 'Workflow' 'Workload' 'company-based project'
 'digital technology' 'e-commerce' 'eBusiness' 'gender'
 'industry-based project']

In [11]:

def text_save(filename, data):#filename为写入CSV文件的路径，data为要写入数据列表.

    file = open(filename,'a')

    for i in range(len(data)):

        s = str(data[i]).replace('[','').replace(']','')#去除[],这两行按数据不同，可以选择

        s = s.replace("'",'').replace(',','') +'\n'   #去除单引号，逗号，每行末尾追加换行符

        file.write(s)

    file.close()

    print("保存文件成功") 
    
text_save("EBM TAG.txt", Tag_final_list)

保存文件成功

In [11]:
def tag_check(project_tags,tag):
    if tag in project_tags:
        return 1
    else:
        return 0

for tag in Tag_final_list:

    df[tag]= df.apply(lambda x: tag_check(x.PROJECT_TAGS,tag),axis =1 )
    
df.head()

,SUPERVISOR,PROJECT_TITLE,PROJECT_DESCRIPTION,PROJECT_TAGS,project_id,supervisor_id,AR-VR,Accountancy,Action Research,Aeronautical,...,Warehousing,Web 2.0,Workflow,Workload,company-based project,digital technology,e-commerce,eBusiness,gender,industry-based project
0,Amanda Dowd,Student Defined Project in the area of Educati...,The areas that I would be interested in superv...,"Information management,Social media,eBusiness,...",1,12,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,Amanda Dowd,The use of on-line technology in academic cour...,INTRODUCTION\r\n\r\nWith increasing numbers of...,"Programme management,Information management,eB...",2,12,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,Nigel Denton,Student proposed project normally in Engineeri...,If you are thinking about a project in the are...,"eBusiness,Financial issues,Innovation,Entrepre...",3,159,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,Des Doran,Sustainable Operations,Exploring the impact of sustainable issues upo...,"Operational issues,Sustainability,Sustainable ...",4,58,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Des Doran,Operations Strategy,This project should explore how strategic posi...,"Supply chain,Operational issues,Strategic mana...",5,58,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df.drop(columns=['PROJECT_TITLE','PROJECT_TAGS'],inplace=True)
print(df.shape)

(737, 270)

In [13]:
for tag in Tag_final_list:

    df[tag]= df.apply(lambda x: tag_check(x.PROJECT_TAGS,tag),axis =1 )
df.drop(columns=['PROJECT_TITLE','PROJECT_TAGS'],inplace=True)    
df.head()

,SUPERVISOR,PROJECT_DESCRIPTION,project_id,supervisor_id,AR-VR,Accountancy,Action Research,Aeronautical,Aerospace,Africa,...,Warehousing,Web 2.0,Workflow,Workload,company-based project,digital technology,e-commerce,eBusiness,gender,industry-based project
0,Amanda Dowd,The areas that I would be interested in superv...,1,12,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,Amanda Dowd,INTRODUCTION\r\n\r\nWith increasing numbers of...,2,12,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,Nigel Denton,If you are thinking about a project in the are...,3,159,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,Des Doran,Exploring the impact of sustainable issues upo...,4,58,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Des Doran,This project should explore how strategic posi...,5,58,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df.to_csv("eBM_cleaned_data.csv", index=False)